### ISSUE TITLE
Reducing amount of boilerplate code by using records

### ISSUE THREAD

**Issue by CountRick** [wdt-dev/weigandt-gpt-slack-bot#4]
Can we replace some boilerplate code in classes like CommandDto by using records instead of classes?

**Comment by konstantin-umanets** [comment]
CommandDto was renamed to QuestionDto, the code contains also logic to create Dto from different sorts of Event objects and logic to select ts or threadTs to answer in the thread. So the easiness of records creates the complexity in the other code parts where this record will be used
